namespace CustomFileGenerators
{
	internal class Constants
	{
		public static string DEFAULT_FILE_EXTENSION = ".g.cs";
		public static string FILE_HEADER = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CustomFileGenerators.ObservablePropertyGenerator.
//     Generator Version: {0}
//     Runtime Version: {1}
//
//     Documentation, Examples, Bug Reports, Community @
//     http://CustomFileGenerators.codeplex.com
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

";
		public static string USING_REGEX = "(using [A-Za-z.]+;)";
		public static string NAMESPACE_REGEX = "namespace [A-Za-z0-9_.]+";
		public static string CLASS_REGEX = "class [A-Za-z0-9_<>, ]+";
		public static string GOP_ATTRIBUTE = "GenerateObservableProperty";
		public const string CLASS_GUID = "C0268385-9DF3-4078-A512-4E474728685A";
	}
}
